# Generated by Django 5.0.1 on 2024-01-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_id", models.CharField(default="", max_length=16)),
                ("message_timestamp", models.DateTimeField()),
                ("message_content", models.TextField()),
                ("author_id", models.CharField(default="", max_length=16)),
            ],
        ),
    ]
